anchor_version = "0.17.0"

[programs.mainnet]
tokadapt = "tokdh9ZbWPxkFzqsKqeAwLDk6J6a8NBZtQanVuuENxa"

[programs.localnet]
tokadapt = "tokdh9ZbWPxkFzqsKqeAwLDk6J6a8NBZtQanVuuENxa"

[[test.genesis]]
address = "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
program = "fixtures/smart_wallet.so"

[[test.genesis]]
address = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
program = "fixtures/spl-governance.so"

[[test.genesis]]
address = "kedgrkbZ5TcjRz2fSpZMcasWzyxd8SuEaXoGfbkPddc"
program = "fixtures/kedgeree.so"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm _test"

